version: '3' 
 
services: 
 
  graph-node: 
    image: graphprotocol/graph-node 
    ports: 
      - '8000:8000' 
      - '8001:8001' 
      - '8020:8020' 
      - '8030:8030' 
    environment: 
      postgres_host: postgres 
      postgres_user: postgres 
      postgres_pass: let-me-in 
      postgres_db: graph-node 
      ipfs: 'http://ipfs:5001' 
      ethereum: 'http://host.docker.internal:8545' 
    depends_on: 
      - postgres 
      - ipfs 
 
  ipfs: 
    image: ipfs/go-ipfs:v0.4.23 
    ports: 
      - '5001:5001' 
 
  postgres: 
    image: postgres 
    ports: 
      - '5432:5432' 
    environment: 
      POSTGRES_PASSWORD: let-me-in 
